### ISSUE TITLE
Does not configure

### ISSUE THREAD

**Issue by joelhinch** [lloydw/hass-spanet#11]
I have been having issues with the plugin lately, does not seem to be communicating with SpaNet's cloud. Updated to 4.0 and still had same issues. Deleted and tried setting up again and nothing populates, accepts my login details but then it just loads a single heater entity that is empty and unavailable. Are there known issues at the moment with setting up a new config?

**Comment by lloydw** [comment]
Hi there, thanks for reporting this. I’m not aware of any issues creating new configs. 

Unfortunately I’m away at the moment, but I can take a look next week when I get back. Which version of HA are you using?

thanks

**Comment by joelhinch** [comment]
2024.7.2

**Comment by joelhinch** [comment]
Seems to be working now FYI. I didn't do anything or reconfigure anything. Seems to have just randomly populated over time.

**Comment by lloydw** [comment]
Thanks for letting me know, will close this for now
