### ISSUE TITLE
Reaching out

### ISSUE THREAD

**Issue by devbobo** [lloydw/hass-spanet#3]
G'day Lloyd,

I've just come across this project. Nice work !!

I did the initial [reverse engineering](https://gist.github.com/devbobo/b82134291d96f384137e01f39a7f2a01) work on the SpaNet protocol. Since then I have been using a hacked homebridge instance inside home assistant, swearing that I would get around to writing a native python integration for home assistant.

The main reason I'm reaching out is that last week I started writing a fully featured python library for SpaNet. It's not production ready yet, but when it is I'm hoping that you might integrate that into this project with the view to getting this into HA Core.

Cheers,

David

**Comment by lloydw** [comment]
Hey David,

Thanks for reaching out and great work on reverse engineering the protocol, I used that doc extensively while implementing this plugin.

It would be great to work together with your new API to get this integrated with HA Core.

Cheers,
Lloyd

**Comment by devbobo** [comment]
Hey Lloyd,

I reached out via email awhile but you might have missed it.

You can check out my project here, there's probably bugs but hopefully a good place to start.

https://github.com/devbobo/pyspanet

Cheers,

David

**Comment by lloydw** [comment]
pyspanet has been archived
