### ISSUE TITLE
No actions available

### ISSUE THREAD

**Issue by ellyse18** [lloydw/hass-spanet#5]
I tried to add an automation to heat the spa overnight between specific hours using a cheap electricity rate on my power plan. but couldn't see an Action to do it. 

The Device is listed as 'lloydw/hass-spanet' in my automation section. Not sure if that is just due to the way I added the plugin to Home Assistant. There are no Actions associated to the device. I was hoping to see set temperature so I can raise it during certain hours.

Note that I can set the temp successfully using the dashboard manually. Overall this is great, thanks so much for putting it together.

**Comment by lloydw** [comment]
Hi There,

Thanks for the feedback, I've not used Actions before so likely a feature I will need to add some code support for.

For now you can set the temperature in automations by calling the climate service. There is an example here: https://github.com/lloydw/hass-spanet/issues/4#issuecomment-2160508754

Any questions, let me know.

**Comment by ellyse18** [comment]
Thank you, I followed your suggestion and now have a simple working automation to heat the spa.
