### ISSUE TITLE
HomeBridge Code

### ISSUE THREAD

**Issue by joelhinch** [lloydw/hass-spanet#8]
First of all, thank you for picking this project up! Cant wait to have native support of all features in Home Assistant.

I currently use HomeBridge added to Home Assistant as a HomeKit device with the below integration in order to control Power Save via Home Assistant Automations (on and off depending on Solar output)

Assuming the author would be ok, maybe you can borrow code to help speed up the development process?https://github.com/BlaT2512/homebridge-spanet
API https://github.com/BlaT2512/spanet-api

**Comment by lloydw** [comment]
Hi There,

Thanks for reaching out, yes I’m aware of this plugin that’s where a lot of SpaNET developers chat and exchange ideas. It’s what this code was started from.

At this point I have all the functionality I need - automating temps, pumps and tracking status for reports.

However I’m happy to keep adding things as people need them - which functionality would you like to see?

**Comment by joelhinch** [comment]
@lloydw thanks! For me to convert from my hacked together Homebridge addon/Homekit to Home Assistant setup I'd personally need Power Save as priority 1 when/if you get to expanding this further for the community. I use this to automate heating when Solar Production is in excess (switching betwen Off and High Power Save mode). Thanks for putting in the hard work.

**Comment by lloydw** [comment]
Thanks for the input, that’s good feedback. The tricky thing about these kinds of settings is how to expose them to HA. As it’s a number of settings, high, low, off and then start and stop times that are all linked. 

Have you seen any extensions that do this kind of thing well?

**Comment by joelhinch** [comment]
I agree exposing the start and stop time would be a challenge and I am not sure how you would approach that. I have mine set in the app as 24/7 so changing it in HA isn't a personal priority as much is switching it On(High) and Off. 
The SpaNet HomeBridge extension has Power Save exposed as a on/off switch with another modifier switch that defines if on is high(on) or low(off) and off being off.

**Comment by lloydw** [comment]
Hi @joelhinch, I've just released 0.4.0 with support for changing the PowerSave mode
