### ISSUE TITLE
Missing Icon/Branding

### ISSUE THREAD

**Issue by DanielNagy** [lloydw/hass-spanet#9]
Hey,

Thanks for this intergration.

FYI, you can add a brand icons into this Git repo - https://github.com/home-assistant/brands/tree/master/custom_integrations

Import the Spanet logos there in the appropriate format/res/etc

ie, here is the one for the Astral Halo intergration i done. https://github.com/home-assistant/brands/tree/master/custom_integrations/astralpool_halo_chlorinator

Cheers

**Comment by lloydw** [comment]
Thanks, I have been meaning to do this as I need this to be accepted into the official HACS list of addons. Will try get it done this week

**Comment by lloydw** [comment]
It took awhile but I've finally opened a PR: https://github.com/home-assistant/brands/pull/6062

**Comment by lloydw** [comment]
This is now complete
